---
blank_issues_enabled: false
contact_links:
  - name: CoreData with MVVM Pattern Community Support
    url: https://github.com/developer-academy-unina/Tutorial-CoreData-with-MVVM/discussions
    about: Please ask and answer questions here.
